/**
 * skills-template.ts
 *
 * Pure string generator for the Mainlayer agent skills guide.
 * No imports from src/cli/, src/services/, or src/utils/.
 * Zero external dependencies.
 */

export const SKILLS_FILENAME = 'mainlayer-skills.md';

export function generateSkillsMd(): string {
  return `# Mainlayer CLI — Agent Skills Guide

> Generated by \`@mainlayer/cli\` postinstall. All commands support \`--json\` for machine-readable output.

---

## Setup

### Required Environment Variables

| Variable | Purpose |
|----------|---------|
| \`MAINLAYER_API_KEY\` | Authenticates API and MCP requests. Get from \`mainlayer auth api-key create --label "my-agent" --json\` |
| \`MAINLAYER_WALLET_PASSPHRASE\` | Unlocks the encrypted wallet for signing without an interactive prompt (headless/agent mode) |

### Optional Environment Variables

| Variable | Default | Purpose |
|----------|---------|---------|
| \`MAINLAYER_API_URL\` | \`https://api.mainlayer.io\` | Override the API base URL (staging, local dev) |
| \`MAINLAYER_SOLANA_NETWORK\` | \`solana:mainnet\` | Override Solana network (e.g. \`solana:devnet\`) |

### Flags Available on All Commands

- \`--json\` — Output structured JSON to stdout. Also auto-enabled when stdout is not a TTY.
- \`--api-key <key>\` — Per-command API key override (overrides \`MAINLAYER_API_KEY\` env var).

### Exit Codes

| Code | Meaning |
|------|---------|
| \`0\` | Success |
| \`1\` | General error |
| \`2\` | Authentication error (re-authenticate with \`mainlayer auth login\`) |
| \`3\` | Not found (resource, subscription, invoice, etc. does not exist) |
| \`4\` | Validation error (invalid input, missing required field) |
| \`5\` | Already exists (duplicate resource slug, coupon code, etc.) |

---

## Vendor Quick-Start

Step-by-step for an AI agent acting as a **vendor** (selling digital resources):

\`\`\`bash
# 1. Register an account
mainlayer auth register --email vendor@example.com --password YourP@ssw0rd --json

# 2. Create an API key and save it to MAINLAYER_API_KEY
mainlayer auth api-key create --label "my-agent" --json
# → { "key": "sk_live_...", "label": "my-agent", "id": "..." }
export MAINLAYER_API_KEY=sk_live_...

# 3. Create an encrypted wallet (set MAINLAYER_WALLET_PASSPHRASE for headless use)
export MAINLAYER_WALLET_PASSPHRASE=my-secure-passphrase
mainlayer wallet create --json
# → { "address": "SolanaPublicKey...", "created": true }

# 4. Create a resource
mainlayer resource create \\
  --slug my-api \\
  --description "My AI API endpoint" \\
  --price 0.01 \\
  --fee-model per_call \\
  --type api \\
  --json
# → { "id": "res_...", "slug": "my-api", "status": "active" }

# 5. Add a subscription pricing plan
mainlayer resource plan create \\
  --resource-id res_... \\
  --name "Basic" \\
  --price 9.99 \\
  --interval monthly \\
  --json
# → { "id": "plan_...", "name": "Basic", "price": 9.99 }

# 6. Configure your webhook to receive payment events
mainlayer webhook update --url https://example.com/webhooks --json
# → { "url": "https://example.com/webhooks", "configured": true }
\`\`\`

---

## Buyer Quick-Start

Step-by-step for an AI agent acting as a **buyer** (purchasing digital resources):

\`\`\`bash
# 1. Register an account
mainlayer auth register --email buyer@example.com --password YourP@ssw0rd --json

# 2. Create and fund a wallet (fund with SOL + USDC before buying)
export MAINLAYER_WALLET_PASSPHRASE=my-secure-passphrase
mainlayer wallet create --json
# → { "address": "SolanaPublicKey...", "created": true }

# 3. Discover available resources
mainlayer discover --json
# → [{ "id": "res_...", "slug": "my-api", "price": 0.01, "fee_model": "per_call" }]

# 4. Buy a resource (X402 on-chain payment)
mainlayer buy res_... --json
# → { "payment_id": "pay_...", "status": "confirmed", "entitlement_id": "ent_..." }

# 5. Verify access
mainlayer entitlements --json
# → [{ "id": "ent_...", "resource_id": "res_...", "status": "active" }]
\`\`\`

---

## Command Reference

### \`mainlayer auth\` — Authentication & API Keys

**Subcommands:**

| Subcommand | Description | Key Flags |
|------------|-------------|-----------|
| \`register\` | Create a new account | \`--email\`, \`--password\` |
| \`login\` | Log in and receive a JWT | \`--email\`, \`--password\` |
| \`logout\` | Clear stored JWT | — |
| \`status\` | Show current auth state | — |
| \`api-key create\` | Create an API key | \`--label\` |
| \`api-key list\` | List all API keys | — |
| \`api-key revoke\` | Revoke an API key by ID | \`<key-id>\` |

**JSON output shape:**
\`\`\`json
// auth register / login
{ "token": "jwt...", "email": "...", "user_id": "..." }

// api-key create
{ "id": "...", "key": "sk_live_...", "label": "..." }
\`\`\`

---

### \`mainlayer wallet\` — Encrypted Local Wallet

**Subcommands:**

| Subcommand | Description | Key Flags |
|------------|-------------|-----------|
| \`create\` | Generate new Solana keypair, encrypt at rest | — |
| \`import\` | Import existing keypair (base58 or mnemonic) | \`--key\`, \`--mnemonic\` |
| \`address\` | Print the wallet's public key | — |
| \`balance\` | Show SOL + USDC balances | — |
| \`export\` | Export private key (requires passphrase confirmation) | — |

**JSON output shape:**
\`\`\`json
// wallet create / import
{ "address": "SolPublicKey...", "created": true }

// wallet balance
{ "sol": 1.5, "usdc": 100.00, "address": "SolPublicKey..." }
\`\`\`

---

### \`mainlayer config\` — CLI Configuration

**Subcommands:**

| Subcommand | Description | Key Flags |
|------------|-------------|-----------|
| \`get\` | Get a config value | \`<key>\` |
| \`set\` | Set a config value | \`<key> <value>\` |

---

### \`mainlayer resource\` — Resource Management (Vendor)

**Subcommands:**

| Subcommand | Description | Key Flags |
|------------|-------------|-----------|
| \`create\` | Register a new resource | \`--slug\`, \`--description\`, \`--price\`, \`--fee-model\`, \`--type\` |
| \`list\` | List all your resources | \`--page\`, \`--limit\` |
| \`get\` | Get a specific resource | \`<resource-id>\` |
| \`update\` | Update a resource | \`<resource-id>\`, \`--description\`, \`--price\` |
| \`delete\` | Delete a resource | \`<resource-id>\`, \`--force\` |
| \`plan create\` | Add a subscription plan | \`--resource-id\`, \`--name\`, \`--price\`, \`--interval\` |
| \`plan list\` | List plans for a resource | \`--resource-id\` |
| \`plan update\` | Update a plan | \`--plan-id\`, \`--price\` |
| \`plan delete\` | Delete a plan | \`--plan-id\` |
| \`quota set\` | Set per-wallet rate limit | \`--resource-id\`, \`--wallet\`, \`--calls\`, \`--period\` |
| \`quota get\` | Get current quota | \`--resource-id\`, \`--wallet\` |
| \`quota delete\` | Remove quota limit | \`--resource-id\`, \`--wallet\` |

**JSON output shape:**
\`\`\`json
// resource create
{ "id": "res_...", "slug": "my-api", "status": "active", "price": 0.01, "fee_model": "per_call" }
\`\`\`

---

### \`mainlayer coupon\` — Discount Codes (Vendor)

**Subcommands:**

| Subcommand | Description | Key Flags |
|------------|-------------|-----------|
| \`create\` | Create a discount coupon | \`--code\`, \`--discount\`, \`--resource-id\`, \`--expires\` |
| \`list\` | List your coupons | \`--resource-id\` |
| \`delete\` | Delete a coupon | \`<coupon-id>\` |

**Note:** Coupon codes are automatically uppercased before API calls.

---

### \`mainlayer webhook\` — Webhook Management (Vendor)

**Subcommands:**

| Subcommand | Description | Key Flags |
|------------|-------------|-----------|
| \`update\` | Set or update webhook URL | \`--url\` |
| \`logs\` | View recent webhook delivery logs | \`--resource-id\` |
| \`retry\` | Retry a failed delivery | \`<log-id>\` |
| \`rotate-secret\` | Rotate webhook signing secret | \`--force\` |

---

### \`mainlayer earnings\` — Revenue Summary (Vendor)

Shows revenue summary with period expansion and daily totals.

**Key flags:** \`--resource-id\`, \`--period\` (default: \`30d\`), \`--from\`, \`--to\`

**JSON output shape:**
\`\`\`json
{ "total_usdc": 123.45, "period": "30d", "breakdown": [{ "date": "...", "amount": 4.5 }] }
\`\`\`

---

### \`mainlayer metrics\` — Usage Analytics (Vendor)

Shows per-resource aggregate analytics.

**Key flags:** \`--resource-id\`

**JSON output shape:**
\`\`\`json
{ "calls": 1024, "unique_buyers": 12, "errors": 3, "resource_id": "res_..." }
\`\`\`

---

### \`mainlayer discover\` — Browse Resources (Buyer, no auth required)

**Key flags:** \`--query\`, \`--type\`, \`--fee-model\`, \`--max-price\`, \`--page\`, \`--limit\`

**JSON output shape:**
\`\`\`json
[{ "id": "res_...", "slug": "...", "description": "...", "price": 0.01, "fee_model": "per_call" }]
\`\`\`

---

### \`mainlayer buy\` — Purchase a Resource (Buyer)

X402 on-chain payment flow: prepare → sign → submit.

**Usage:** \`mainlayer buy <resource-id> [--json]\`

**JSON output shape:**
\`\`\`json
{ "payment_id": "pay_...", "status": "confirmed", "entitlement_id": "ent_...", "tx_signature": "..." }
\`\`\`

**Error hints:**
- \`plan_required\` — resource requires a subscription plan; use \`mainlayer subscribe approve\`
- \`tx_expired\` — transaction TTL expired; retry the buy command

---

### \`mainlayer entitlements\` — View Access Grants (Buyer)

**Key flags:** \`--resource-id\`

**JSON output shape:**
\`\`\`json
[{ "id": "ent_...", "resource_id": "res_...", "status": "active", "expires_at": "..." }]
\`\`\`

---

### \`mainlayer subscribe\` — Subscription Management

**Subcommands:**

| Subcommand | Description | Key Flags |
|------------|-------------|-----------|
| \`approve\` | Approve a subscription (signs USDC delegate on-chain) | \`--resource-id\`, \`--plan-id\` |
| \`pause\` | Pause an active subscription | \`<subscription-id>\` |
| \`resume\` | Resume a paused subscription | \`<subscription-id>\` |
| \`cancel\` | Cancel a subscription | \`<subscription-id>\`, \`--force\` |
| \`list\` | List your subscriptions | \`--resource-id\` |
| \`get\` | Get a specific subscription | \`<subscription-id>\` |

**JSON output shape:**
\`\`\`json
{ "id": "sub_...", "resource_id": "res_...", "plan_id": "plan_...", "status": "active" }
\`\`\`

---

### \`mainlayer invoices\` — Invoice History

**Key flags:** \`--resource-id\`

**JSON output shape:**
\`\`\`json
[{ "id": "inv_...", "amount": 9.99, "status": "paid", "created_at": "...", "resource_id": "res_..." }]
\`\`\`

---

### \`mainlayer refund\` — Request a Refund

**Usage:** \`mainlayer refund request <payment-id> [--json]\`

**JSON output shape:**
\`\`\`json
{ "id": "ref_...", "payment_id": "pay_...", "status": "pending", "amount": 0.01 }
\`\`\`

---

### \`mainlayer dispute\` — Dispute Management

**Subcommands:**

| Subcommand | Description | Key Flags |
|------------|-------------|-----------|
| \`create\` | Open a dispute on a payment | \`--payment-id\`, \`--reason\` |
| \`list\` | List disputes (vendor-scoped) | \`--resource-id\` |

**JSON output shape:**
\`\`\`json
// dispute create
{ "id": "dis_...", "payment_id": "pay_...", "status": "open", "reason": "..." }
\`\`\`

---

### \`mainlayer setup\` — MCP Auto-Configuration

Re-runs the platform detection and MCP registration that occurs on \`npm install\`.

**Key flags:** \`--force\` (overwrite existing entries), \`--json\`

**JSON output shape:**
\`\`\`json
{
  "platforms": [
    { "name": "Claude Code", "configured": true, "skills_dropped": true, "error": null },
    { "name": "Cursor", "configured": true, "skills_dropped": true, "error": null }
  ]
}
\`\`\`

---

## Agent Notes

### Headless / Non-Interactive Mode

Set \`MAINLAYER_WALLET_PASSPHRASE\` as an environment variable to avoid the interactive passphrase prompt when any command needs to sign a transaction:

\`\`\`bash
export MAINLAYER_WALLET_PASSPHRASE=your-passphrase
mainlayer buy res_... --json
\`\`\`

### CI / Automated Environments

When \`CI=true\` is set, the CLI skips interactive output formatting (spinners, color, prompts). All commands still function normally.

### JSON Output

All commands return valid JSON when:
- \`--json\` flag is set, OR
- stdout is not a TTY (e.g., piped output, CI environment)

### Programmatic Error Handling

Use exit codes to determine success or failure without parsing stderr:

\`\`\`bash
mainlayer buy res_... --json
if [ $? -eq 0 ]; then
  echo "Payment confirmed"
elif [ $? -eq 2 ]; then
  echo "Auth error — check MAINLAYER_API_KEY"
fi
\`\`\`

### MCP Server Authentication

When using the Mainlayer MCP server via Claude Code, Cursor, or other AI platforms, set \`MAINLAYER_API_KEY\` in your environment. The MCP config written by postinstall uses \`"Authorization": "Bearer \${MAINLAYER_API_KEY}"\` with env var interpolation where supported.

### Claude Desktop Users

Claude Desktop does **not** support remote HTTP MCP servers via \`claude_desktop_config.json\`. To connect Claude Desktop to the Mainlayer MCP server, use **Settings > Connectors** in the Claude Desktop UI and add: \`https://api.mainlayer.io/mcp\`.
`;
}
